function request = getRequestTemplate()
% Create a parameter template for HEDTools web service request.

request = struct('service', '', ...
                 'schema_version', '', ...
                 'schema_url', '', ...
                 'schema_string', '', ...
                 'sidecar_string', '', ...
                 'events_string', '', ...
                 'spreadsheet_string', '', ...
                 'remodel_string', '', ...
                 'columns_categorical', '', ...
                 'columns_value', '', ...
                 'tag_columns', '', ...
                 'queries', '', ...
                 'query_names', '', ...
                 'remove_types', '', ...
                 'check_for_warnings', false, ...
                 'expand_context', true, ...
                 'expand_defs', false, ...
                 'include_summaries', false, ...
                 'include_descriptions', true, ...
                 'replace_defs', false);

end