function data = getTestData()
%% Return the test data in a struct for running the services.

    %% Read the JSON sidecar into a string for all examples
    data = struct('descPrefix', '', 'eventsText', '', ...
                  'jsonBadText', '', 'jsonText', '', 'labelPrefix', '', ...
                  'schemaUrl', '', 'schemaText', '', ...
                  'spreadsheetText', '', 'spreadsheetTextInvalid', '');
    myPath = mfilename("fullpath");  
    [curDir, ~, ~] = fileparts(myPath);
    dataPath = fullfile(curDir, filesep, '..', ...
                        filesep, '..', filesep, 'data', filesep)

    demoPath = fullfile(dataPath, 'eeg_ds003645s_hed_demo', filesep);
    eventsFile = ['sub-002' filesep 'ses-1' filesep 'eeg' filesep ...
                  'sub-002_ses-1_task-FacePerception_run-1_events.tsv']
    % libraryPath = '../../../datasets/eeg_ds003645s_hed_library/';
    % data.jsonLibrary = fileread(...
    %     [libraryPath 'task-FacePerception_events.json']);
    data.jsonText = fileread([demoPath 'task-FacePerception_events.json']);
    data.eventsText =  fileread(fullfile(demoPath, eventsFile));
    data.remodel1Text = fileread(...
        [dataPath 'other_data/remove_extra_rmdl.json']);
    data.remodel2Text = fileread( ...
        [dataPath 'other_data/summarize_columns_rmdl.json']);
    data.remodel3Text = fileread(...
        [dataPath 'other_data/summarize_hed_types_rmdl.json']);
    data.jsonBadText = ...
        fileread([dataPath 'other_data/both_types_events_errors.json']);
    data.labelPrefix = 'Property/Informational-property/Label/';
    data.descPrefix = 'Property/Informational-property/Description/';
    data.schemaText = fileread([dataPath 'schema_data/HED8.2.0.xml']);
    data.schemaUrl = ['https://raw.githubusercontent.com/hed-standard/' ...
        'hed-schemas/master/standard_schema/hedxml/HED8.2.0.xml'];
    data.spreadsheetText = fileread(fullfile(dataPath, 'other_data', ...
        filesep, 'LKTEventCodesHED3.tsv'));
    data.spreadsheetTextExtracted = fileread(fullfile(dataPath, ...
        'other_data', filesep, 'task-FacePerception_events_extracted.tsv'));
    data.spreadsheetTextInvalid = fileread(fullfile(dataPath, ...
        'other_data', filesep, 'LKTEventCodesHED2.tsv'));
    data.goodStrings = {'Red,Blue', 'Green', 'White, (Black, Image)'}; 
    data.badStrings = {'Red, Blue, Blech', 'Green', 'White, Black, Binge'}; 
end